### PR TITLE
Added mapping function and demo using single subject sample data 

### PR DESCRIPTION
**Pull request by angelaradulescu**

### CODE REVIEW

**Review by szorowi1 — CHANGES_REQUESTED** [review]
Hey, code looks really good! Requesting the following changes as discussed earlier, but obviously feel free to take or leave as you see fit!

MAIN CODE
- [ ] **Mapping function:** can be moved to demo document as part of "pandas cookbook". For concreteness, mapping can be completed as:

``` python
## Add Feature column to DataFrame.
df['Feature'] = featmap[np.arange(n_trials), df.AoI.values - 1]    # -1 for pythonic 0-indexing
```
Relevant documentation [here](https://docs.scipy.org/doc/numpy/user/basics.indexing.html#indexing-multi-dimensional-arrays).

MATUTILS
- [ ] Your decision about whether you would like to keep those associated with NivLink or in a separate repo for the FHT data.

DEMOS
- [ ] **Mapping**: Add AoI-to-Feature mapping as above.
- [ ] **Sanity check:** Add sanity check testing if our mapping is correct compared to Matlab. One way to do this would be to make sure that the column chosen does indeed contain the correct feature, as would be implied by the "correct" column of the Matlab struct. (Let me know if this doesn't make sense.)
- [ ] **Pandas Cookbook:** Some helpful examples such as (1) removing short fixations; (2) removing fixations after response or before outcome; (3) realigning fixation onset to RT; (4) GroupBy example, averaging over subject/block. If helpful, there are [some examples here](https://github.com/PrincetonUniversity/NivLabChallenge2018/blob/master/SamZ/04_WSLS.ipynb) under *Consistency of Fixations*.
- [ ] **Minor 1**: Maybe limit sample data to first two blocks?
- [ ] **Minor 2**: When visualizing the DataFrame *mapped*, use `mapped.head(n)` to only print the first *n* rows of the DataFrame.
- [ ] **Minor 3:** After calling `plt.title(...)`, add a semicolon to suppress the matplotlib print, i.e. `plt.title(...);`.

**Comment by szorowi1** [comment]
Hey, code looks really good! Requesting the following changes as discussed earlier, but obviously feel free to take or leave as you see fit!

MAIN CODE
- [ ] **Mapping function:** can be moved to demo document as part of "pandas cookbook". For concreteness, mapping can be completed as:

``` python
## Add Feature column to DataFrame.
df['Feature'] = featmap[np.arange(n_trials), df.AoI.values - 1]    # -1 for pythonic 0-indexing
```
Relevant documentation [here](https://docs.scipy.org/doc/numpy/user/basics.indexing.html#indexing-multi-dimensional-arrays).

MATUTILS
- [ ] Your decision about whether you would like to keep those associated with NivLink or in a separate repo for the FHT data.

DEMOS
- [ ] **Mapping**: Add AoI-to-Feature mapping as above.
- [ ] **Sanity check:** Add sanity check testing if our mapping is correct compared to Matlab. One way to do this would be to make sure that the column chosen does indeed contain the correct feature, as would be implied by the "correct" column of the Matlab struct. (Let me know if this doesn't make sense.)
- [ ] **Pandas Cookbook:** Some helpful examples such as (1) removing short fixations; (2) removing fixations after response or before outcome; (3) realigning fixation onset to RT; (4) GroupBy example, averaging over subject/block. If helpful, there are [some examples here](https://github.com/PrincetonUniversity/NivLabChallenge2018/blob/master/SamZ/04_WSLS.ipynb) under *Consistency of Fixations*.
- [ ] **Minor 1**: Maybe limit sample data to first two blocks?
- [ ] **Minor 2**: When visualizing the DataFrame *mapped*, use `mapped.head(n)` to only print the first *n* rows of the DataFrame.
- [ ] **Minor 3:** After calling `plt.title(...)`, add a semicolon to suppress the matplotlib print, i.e. `plt.title(...);`.

**Comment by angelaradulescu** [comment]
Ok, shiny new pull request has been updated! The only item that needs additional discussion, but is perhaps superfluous to this demo, is the sanity check for the mapping function. I have some offline analyses & thoughts to share on Thursday. In the meantime, if the rest looks good to you, let there be merging? 

Speaking of, pd.merge is amazing.

**Review by szorowi1 — APPROVED** [review]

**Comment by szorowi1** [comment]
The demo looks great! Thanks so much for putting it all together!

**Pull request merged**
