### PR TITLE
Added multiple screens functionality. 

### PR DESCRIPTION
**Pull request by angelaradulescu**
Landed on a solution where I provide `add_rectangle_aoi` with a screen ID which tells it which set of screen indices to add the AoI to. Each AoI should be uniquely labeled as before, and also have a screen tag which later enables the user to remap AoIs as needed. 

Checking that I didn't break anything would be most welcome!

### CODE REVIEW

**Comment by angelaradulescu** [comment]
Forgot to update fork, will close and re-open.

**Comment by angelaradulescu** [comment]
I'm super confused... Why does this pull request contain commits which were reviewed in the last one?

**Comment by szorowi1** [comment]
Was the PR requested from a personal fork of the repo? If so, did you git fetch/pull your local copy to reflect the changes made since #10?

**Comment by angelaradulescu** [comment]
Yes, I requested from [my fork](https://github.com/angelaradulescu/NivLink).

And I did a fetch/pull but from that fork to the local repo. But I [didn't update the fork](https://gist.github.com/CristinaSolana/1885435) to reflect changes in [10](https://github.com/nivlab/NivLink/pull/10). Yikes.

**Comment by szorowi1** [comment]
That's my bad! Should have let you know I pushed the RTD to master.

**Comment by angelaradulescu** [comment]
Nah, I should have looked... Manually fixing conflicts now, shouldn't be too painful.

**Comment by angelaradulescu** [comment]
Okay... Conflicts have been resolved and hopefully everything still works.

**Comment by szorowi1** [comment]
Awesome! Merge looks good. As expected, Travis-CI checks are failing since we altered the core structure of the `ScreenInfo` object. Do you want to meet sometime this week to go over the unit tests?

**Comment by angelaradulescu** [comment]
Sure thing, when is good for you?

**Comment by angelaradulescu** [comment]
Ok, Travis is happy, approve at will! 
One more smaller one reflecting the masking function coming your way later today.

**Comment by szorowi1** [comment]
Woot! Any other commits coming down the pike? Otherwise, I'll go ahead and approve!

**Comment by angelaradulescu** [comment]
Not for this one! More in the next one which deals with masking.

**Comment by szorowi1** [comment]
Done! Thanks so much!

**Pull request merged**
